feat: server actions for all stacks

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -6,7 +6,7 @@ echo "styling your work" 🎨✨
 
 
 # Check Prettier standards
-npm run check-format ||
+pnpm run check-format ||
 (
     echo '🤢🤮🤢🤮 Its so ugly!! - Your styling looks disgusting. 🤢🤮🤢🤮
             Prettier Check Failed. Running npm run format...';
@@ -21,18 +21,18 @@ npm run check-format ||
 
 echo '🏗️👷 checking for eslint errors' 🔍🧐
 
-# # Check ESLint Standards
-# npm run check-lint ||
-# 	(
-# 		echo '😤🏀👋😤 Get that beans code out of here! 😤🏀👋😤
-#                 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
-# 		false
-# 	)
+# Check ESLint Standards
+pnpm run lint ||
+	(
+		echo '😤🏀👋😤 Get that beans code out of here! 😤🏀👋😤
+                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
+		false
+	)
 
-# echo '🏗️👷 checking for typescript errors' 🔍🧐
+echo '🏗️👷 checking for typescript errors' 🔍🧐
 
 # Check tsconfig standards
-npm run check-types ||
+pnpm run check-types ||
 	(
 		echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
